/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Scanner;
/**
 *
 * @author Justin Keenan
 */
public class Gameboard {


    /**
     * Creates new form WorldOfCandy
     */
    public Gameboard() {
        initComponents();
        //getPlayers();
        for (int i =0; i< WorldOfSweets.players.length; i++){

            _frame.add(WorldOfSweets.players[i]);

        }
        _frame.setVisible(true);

    }


    //public static void main(String[] args) {
    //  new Gameboard();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _frame = new JFrame();
        start = new StartSquare(new ImageIcon("src/main/resources/images/rainbow2.jpg").getImage());
        sq1 = new JPanel();
        sq2 = new JPanel();
        sq3 = new JPanel();
        sq4 = new JPanel();
        sq5 = new JPanel();
        sq6 = new JPanel();
        sq7 = new JPanel();
        sq8 = new JPanel();
        sq9 = new JPanel();
        sq10 = new JPanel();
        sq11 = new JPanel();
        sq12 = new JPanel();
        sq13 = new JPanel();
        sq14 = new JPanel();
        sq16 = new JPanel();
        sq17 = new JPanel();
        sq18 = new JPanel();
        sq19 = new JPanel();
        sq20 = new JPanel();
        sq21 = new JPanel();
        sq22 = new JPanel();
        sq23 = new JPanel();
        sq24 = new JPanel();
        sq25 = new JPanel();
        sq26 = new JPanel();
        sq27 = new JPanel();
        sq28 = new JPanel();
        sq29 = new JPanel();
        sq30 = new JPanel();
        sq31 = new JPanel();
        sq32 = new JPanel();
        sq34 = new JPanel();
        sq35 = new JPanel();
        sq36 = new JPanel();
        sq37 = new JPanel();
        sq38 = new JPanel();
        sq39 = new JPanel();
        sq40 = new JPanel();
        sq44 = new JPanel();
        sq41 = new JPanel();
        sq43 = new JPanel();
        sq33 = new JPanel();
        sq45 = new JPanel();
        sq46 = new JPanel();
        sq47 = new JPanel();
        sq48 = new JPanel();
        sq49 = new JPanel();
        sq50 = new JPanel();
        sq51 = new JPanel();
        sq52 = new JPanel();
        sq53 = new JPanel();
        sq54 = new JPanel();
        sq55 = new JPanel();
        sq56 = new JPanel();
        sq57 = new JPanel();
        sq58 = new JPanel();
        sq59 = new JPanel();
        sq64 = new JPanel();
        sq60 = new JPanel();
        sq61 = new JPanel();
        sq62 = new JPanel();
        sq63 = new JPanel();
        sq68 = new JPanel();
        sq73 = new JPanel();
        sq75 = new JPanel();
        sq80 = new JPanel();
        sq81 = new JPanel();
        grandmasHouse = new GrannysHouse(new ImageIcon("src/main/resources/images/rainbow1.jpg").getImage());
        sq87 = new JPanel();
        sq86 = new JPanel();
        sq85 = new JPanel();
        sq84 = new JPanel();
        sq82 = new JPanel();
        sq83 = new JPanel();
        sq76 = new JPanel();
        sq77 = new JPanel();
        sq78 = new JPanel();
        sq79 = new JPanel();
        sq72 = new JPanel();
        sq71 = new JPanel();
        sq70 = new JPanel();
        sq69 = new JPanel();
        sq67 = new JPanel();
        sq66 = new JPanel();
        sq65 = new JPanel();
        sq88 = new JPanel();
        sq89 = new JPanel();
        sq90 = new JPanel();
        sq15 = new JPanel();
        sq42 = new JPanel();
        sq74 = new JPanel();
    ///////////////////////////////////
        deckArea = new JPanel();
    ///////////////////////////////////

        _frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        _frame.setSize(1250, 700);
        _frame.setLayout(null);

        //start.setBackground(new Color(255, 255, 255));
        //start.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        //start.setPreferredSize(new Dimension(80, 80));

        GroupLayout startLayout = new GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
            startLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        startLayout.setVerticalGroup(
            startLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(start);
        start.setBounds(20, 480, 80, 80);

        sq1.setBackground(Color.red);
        sq1.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq1.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq1Layout = new GroupLayout(sq1);
        sq1.setLayout(sq1Layout);
        sq1Layout.setHorizontalGroup(
            sq1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq1Layout.setVerticalGroup(
            sq1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq1);
        sq1.setBounds(100, 500, 40, 40);

        sq2.setBackground(Color.yellow);
        sq2.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq2.setMinimumSize(new Dimension(20, 20));
        sq2.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq2Layout = new GroupLayout(sq2);
        sq2.setLayout(sq2Layout);
        sq2Layout.setHorizontalGroup(
            sq2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        sq2Layout.setVerticalGroup(
            sq2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        _frame.add(sq2);
        sq2.setBounds(140, 500, 40, 40);

        sq3.setBackground(Color.blue);
        sq3.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq3.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq3Layout = new GroupLayout(sq3);
        sq3.setLayout(sq3Layout);
        sq3Layout.setHorizontalGroup(
            sq3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq3Layout.setVerticalGroup(
            sq3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq3);
        sq3.setBounds(180, 500, 40, 40);

        sq4.setBackground(Color.green);
        sq4.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq4.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq4Layout = new GroupLayout(sq4);
        sq4.setLayout(sq4Layout);
        sq4Layout.setHorizontalGroup(
            sq4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq4Layout.setVerticalGroup(
            sq4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq4);
        sq4.setBounds(220, 500, 40, 40);

        sq5.setBackground(Color.orange);
        sq5.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq5.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq5Layout = new GroupLayout(sq5);
        sq5.setLayout(sq5Layout);
        sq5Layout.setHorizontalGroup(
            sq5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq5Layout.setVerticalGroup(
            sq5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq5);
        sq5.setBounds(220, 460, 40, 40);

        sq6.setBackground(Color.red);
        sq6.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq6.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq6Layout = new GroupLayout(sq6);
        sq6.setLayout(sq6Layout);
        sq6Layout.setHorizontalGroup(
            sq6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq6Layout.setVerticalGroup(
            sq6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq6);
        sq6.setBounds(220, 420, 40, 40);

        sq7.setBackground(Color.yellow);
        sq7.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq7.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq7Layout = new GroupLayout(sq7);
        sq7.setLayout(sq7Layout);
        sq7Layout.setHorizontalGroup(
            sq7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq7Layout.setVerticalGroup(
            sq7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq7);
        sq7.setBounds(220, 380, 40, 40);

        sq8.setBackground(Color.blue);
        sq8.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq8.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq8Layout = new GroupLayout(sq8);
        sq8.setLayout(sq8Layout);
        sq8Layout.setHorizontalGroup(
            sq8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq8Layout.setVerticalGroup(
            sq8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq8);
        sq8.setBounds(260, 380, 40, 40);

        sq9.setBackground(Color.green);
        sq9.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq9.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq9Layout = new GroupLayout(sq9);
        sq9.setLayout(sq9Layout);
        sq9Layout.setHorizontalGroup(
            sq9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq9Layout.setVerticalGroup(
            sq9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq9);
        sq9.setBounds(300, 380, 40, 40);

        sq10.setBackground(Color.orange);
        sq10.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq10.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq10Layout = new GroupLayout(sq10);
        sq10.setLayout(sq10Layout);
        sq10Layout.setHorizontalGroup(
            sq10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq10Layout.setVerticalGroup(
            sq10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq10);
        sq10.setBounds(340, 380, 40, 40);

        sq11.setBackground(Color.red);
        sq11.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq11.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq11Layout = new GroupLayout(sq11);
        sq11.setLayout(sq11Layout);
        sq11Layout.setHorizontalGroup(
            sq11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq11Layout.setVerticalGroup(
            sq11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq11);
        sq11.setBounds(380, 380, 40, 40);

        sq12.setBackground(Color.yellow);
        sq12.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq12.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq12Layout = new GroupLayout(sq12);
        sq12.setLayout(sq12Layout);
        sq12Layout.setHorizontalGroup(
            sq12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq12Layout.setVerticalGroup(
            sq12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq12);
        sq12.setBounds(380, 420, 40, 40);

        sq13.setBackground(Color.blue);
        sq13.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq13.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq13Layout = new GroupLayout(sq13);
        sq13.setLayout(sq13Layout);
        sq13Layout.setHorizontalGroup(
            sq13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq13Layout.setVerticalGroup(
            sq13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq13);
        sq13.setBounds(380, 460, 40, 40);

        sq14.setBackground(Color.green);
        sq14.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq14.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq14Layout = new GroupLayout(sq14);
        sq14.setLayout(sq14Layout);
        sq14Layout.setHorizontalGroup(
            sq14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq14Layout.setVerticalGroup(
            sq14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq14);
        sq14.setBounds(380, 500, 40, 40);

        sq16.setBackground(Color.red);
        sq16.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq16.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq16Layout = new GroupLayout(sq16);
        sq16.setLayout(sq16Layout);
        sq16Layout.setHorizontalGroup(
            sq16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq16Layout.setVerticalGroup(
            sq16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq16);
        sq16.setBounds(460, 500, 40, 40);

        sq17.setBackground(Color.yellow);
        sq17.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq17.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq17Layout = new GroupLayout(sq17);
        sq17.setLayout(sq17Layout);
        sq17Layout.setHorizontalGroup(
            sq17Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq17Layout.setVerticalGroup(
            sq17Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq17);
        sq17.setBounds(500, 500, 40, 40);

        sq18.setBackground(Color.blue);
        sq18.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq18.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq18Layout = new GroupLayout(sq18);
        sq18.setLayout(sq18Layout);
        sq18Layout.setHorizontalGroup(
            sq18Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq18Layout.setVerticalGroup(
            sq18Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq18);
        sq18.setBounds(540, 500, 40, 40);

        sq19.setBackground(Color.green);
        sq19.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq19.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq19Layout = new GroupLayout(sq19);
        sq19.setLayout(sq19Layout);
        sq19Layout.setHorizontalGroup(
            sq19Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq19Layout.setVerticalGroup(
            sq19Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq19);
        sq19.setBounds(580, 500, 40, 40);

        sq20.setBackground(Color.orange);
        sq20.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq20.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq20Layout = new GroupLayout(sq20);
        sq20.setLayout(sq20Layout);
        sq20Layout.setHorizontalGroup(
            sq20Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq20Layout.setVerticalGroup(
            sq20Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq20);
        sq20.setBounds(620, 500, 40, 40);

        sq21.setBackground(Color.red);
        sq21.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq21.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq21Layout = new GroupLayout(sq21);
        sq21.setLayout(sq21Layout);
        sq21Layout.setHorizontalGroup(
            sq21Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq21Layout.setVerticalGroup(
            sq21Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq21);
        sq21.setBounds(660, 500, 40, 40);

        sq22.setBackground(Color.yellow);
        sq22.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq22.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq22Layout = new GroupLayout(sq22);
        sq22.setLayout(sq22Layout);
        sq22Layout.setHorizontalGroup(
            sq22Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq22Layout.setVerticalGroup(
            sq22Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq22);
        sq22.setBounds(700, 500, 40, 40);

        sq23.setBackground(Color.blue);
        sq23.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq23.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq23Layout = new GroupLayout(sq23);
        sq23.setLayout(sq23Layout);
        sq23Layout.setHorizontalGroup(
            sq23Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq23Layout.setVerticalGroup(
            sq23Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq23);
        sq23.setBounds(700, 460, 40, 40);

        sq24.setBackground(Color.green);
        sq24.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq24.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq24Layout = new GroupLayout(sq24);
        sq24.setLayout(sq24Layout);
        sq24Layout.setHorizontalGroup(
            sq24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq24Layout.setVerticalGroup(
            sq24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq24);
        sq24.setBounds(700, 420, 40, 40);

        sq25.setBackground(Color.orange);
        sq25.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq25.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq25Layout = new GroupLayout(sq25);
        sq25.setLayout(sq25Layout);
        sq25Layout.setHorizontalGroup(
            sq25Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq25Layout.setVerticalGroup(
            sq25Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq25);
        sq25.setBounds(660, 420, 40, 40);

        sq26.setBackground(Color.red);
        sq26.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq26.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq26Layout = new GroupLayout(sq26);
        sq26.setLayout(sq26Layout);
        sq26Layout.setHorizontalGroup(
            sq26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq26Layout.setVerticalGroup(
            sq26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq26);
        sq26.setBounds(620, 420, 40, 40);

        sq27.setBackground(Color.yellow);
        sq27.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq27.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq27Layout = new GroupLayout(sq27);
        sq27.setLayout(sq27Layout);
        sq27Layout.setHorizontalGroup(
            sq27Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq27Layout.setVerticalGroup(
            sq27Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq27);
        sq27.setBounds(580, 420, 40, 40);

        sq28.setBackground(Color.blue);
        sq28.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq28.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq28Layout = new GroupLayout(sq28);
        sq28.setLayout(sq28Layout);
        sq28Layout.setHorizontalGroup(
            sq28Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq28Layout.setVerticalGroup(
            sq28Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq28);
        sq28.setBounds(540, 420, 40, 40);

        sq29.setBackground(Color.green);
        sq29.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq29.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq29Layout = new GroupLayout(sq29);
        sq29.setLayout(sq29Layout);
        sq29Layout.setHorizontalGroup(
            sq29Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq29Layout.setVerticalGroup(
            sq29Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq29);
        sq29.setBounds(500, 420, 40, 40);

        sq30.setBackground(Color.orange);
        sq30.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq30.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq30Layout = new GroupLayout(sq30);
        sq30.setLayout(sq30Layout);
        sq30Layout.setHorizontalGroup(
            sq30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq30Layout.setVerticalGroup(
            sq30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq30);
        sq30.setBounds(500, 380, 40, 40);

        sq31.setBackground(Color.red);
        sq31.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq31.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq31Layout = new GroupLayout(sq31);
        sq31.setLayout(sq31Layout);
        sq31Layout.setHorizontalGroup(
            sq31Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq31Layout.setVerticalGroup(
            sq31Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq31);
        sq31.setBounds(500, 340, 40, 40);

        sq32.setBackground(Color.yellow);
        sq32.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq32.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq32Layout = new GroupLayout(sq32);
        sq32.setLayout(sq32Layout);
        sq32Layout.setHorizontalGroup(
            sq32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq32Layout.setVerticalGroup(
            sq32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq32);
        sq32.setBounds(500, 300, 40, 40);

        sq34.setBackground(Color.green);
        sq34.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq34.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq34Layout = new GroupLayout(sq34);
        sq34.setLayout(sq34Layout);
        sq34Layout.setHorizontalGroup(
            sq34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq34Layout.setVerticalGroup(
            sq34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq34);
        sq34.setBounds(540, 260, 40, 40);

        sq35.setBackground(Color.orange);
        sq35.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq35.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq35Layout = new GroupLayout(sq35);
        sq35.setLayout(sq35Layout);
        sq35Layout.setHorizontalGroup(
            sq35Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq35Layout.setVerticalGroup(
            sq35Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq35);
        sq35.setBounds(580, 260, 40, 40);

        sq36.setBackground(Color.red);
        sq36.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq36.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq36Layout = new GroupLayout(sq36);
        sq36.setLayout(sq36Layout);
        sq36Layout.setHorizontalGroup(
            sq36Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq36Layout.setVerticalGroup(
            sq36Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq36);
        sq36.setBounds(620, 260, 40, 40);

        sq37.setBackground(Color.yellow);
        sq37.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq37.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq37Layout = new GroupLayout(sq37);
        sq37.setLayout(sq37Layout);
        sq37Layout.setHorizontalGroup(
            sq37Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq37Layout.setVerticalGroup(
            sq37Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq37);
        sq37.setBounds(660, 260, 40, 40);

        sq38.setBackground(Color.blue);
        sq38.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq38.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq38Layout = new GroupLayout(sq38);
        sq38.setLayout(sq38Layout);
        sq38Layout.setHorizontalGroup(
            sq38Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq38Layout.setVerticalGroup(
            sq38Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq38);
        sq38.setBounds(700, 260, 40, 40);

        sq39.setBackground(Color.green);
        sq39.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq39.setMinimumSize(new Dimension(20, 20));
        sq39.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq39Layout = new GroupLayout(sq39);
        sq39.setLayout(sq39Layout);
        sq39Layout.setHorizontalGroup(
            sq39Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        sq39Layout.setVerticalGroup(
            sq39Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        _frame.add(sq39);
        sq39.setBounds(740, 260, 40, 40);

        sq40.setBackground(Color.orange);
        sq40.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq40.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq40Layout = new GroupLayout(sq40);
        sq40.setLayout(sq40Layout);
        sq40Layout.setHorizontalGroup(
            sq40Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq40Layout.setVerticalGroup(
            sq40Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq40);
        sq40.setBounds(780, 260, 40, 40);

        sq44.setBackground(Color.green);
        sq44.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq44.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq44Layout = new GroupLayout(sq44);
        sq44.setLayout(sq44Layout);
        sq44Layout.setHorizontalGroup(
            sq44Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq44Layout.setVerticalGroup(
            sq44Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq44);
        sq44.setBounds(820, 140, 40, 40);

        sq41.setBackground(Color.red);
        sq41.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq41.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq41Layout = new GroupLayout(sq41);
        sq41.setLayout(sq41Layout);
        sq41Layout.setHorizontalGroup(
            sq41Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq41Layout.setVerticalGroup(
            sq41Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq41);
        sq41.setBounds(820, 260, 40, 40);

        sq43.setBackground(Color.blue);
        sq43.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq43.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq43Layout = new GroupLayout(sq43);
        sq43.setLayout(sq43Layout);
        sq43Layout.setHorizontalGroup(
            sq43Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq43Layout.setVerticalGroup(
            sq43Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq43);
        sq43.setBounds(820, 180, 40, 40);

        sq33.setBackground(Color.blue);
        sq33.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq33.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq33Layout = new GroupLayout(sq33);
        sq33.setLayout(sq33Layout);
        sq33Layout.setHorizontalGroup(
            sq33Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq33Layout.setVerticalGroup(
            sq33Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq33);
        sq33.setBounds(500, 260, 40, 40);

        sq45.setBackground(Color.orange);
        sq45.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq45.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq45Layout = new GroupLayout(sq45);
        sq45.setLayout(sq45Layout);
        sq45Layout.setHorizontalGroup(
            sq45Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq45Layout.setVerticalGroup(
            sq45Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq45);
        sq45.setBounds(780, 140, 40, 40);

        sq46.setBackground(Color.red);
        sq46.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq46.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq46Layout = new GroupLayout(sq46);
        sq46.setLayout(sq46Layout);
        sq46Layout.setHorizontalGroup(
            sq46Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq46Layout.setVerticalGroup(
            sq46Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq46);
        sq46.setBounds(740, 140, 40, 40);

        sq47.setBackground(Color.yellow);
        sq47.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq47.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq47Layout = new GroupLayout(sq47);
        sq47.setLayout(sq47Layout);
        sq47Layout.setHorizontalGroup(
            sq47Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq47Layout.setVerticalGroup(
            sq47Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq47);
        sq47.setBounds(700, 140, 40, 40);

        sq48.setBackground(Color.blue);
        sq48.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq48.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq48Layout = new GroupLayout(sq48);
        sq48.setLayout(sq48Layout);
        sq48Layout.setHorizontalGroup(
            sq48Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq48Layout.setVerticalGroup(
            sq48Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq48);
        sq48.setBounds(660, 140, 40, 40);

        sq49.setBackground(Color.green);
        sq49.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq49.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq49Layout = new GroupLayout(sq49);
        sq49.setLayout(sq49Layout);
        sq49Layout.setHorizontalGroup(
            sq49Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq49Layout.setVerticalGroup(
            sq49Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq49);
        sq49.setBounds(660, 180, 40, 40);

        sq50.setBackground(Color.orange);
        sq50.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq50.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq50Layout = new GroupLayout(sq50);
        sq50.setLayout(sq50Layout);
        sq50Layout.setHorizontalGroup(
            sq50Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq50Layout.setVerticalGroup(
            sq50Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq50);
        sq50.setBounds(620, 180, 40, 40);

        sq51.setBackground(Color.red);
        sq51.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq51.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq51Layout = new GroupLayout(sq51);
        sq51.setLayout(sq51Layout);
        sq51Layout.setHorizontalGroup(
            sq51Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq51Layout.setVerticalGroup(
            sq51Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq51);
        sq51.setBounds(580, 180, 40, 40);

        sq52.setBackground(Color.yellow);
        sq52.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq52.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq52Layout = new GroupLayout(sq52);
        sq52.setLayout(sq52Layout);
        sq52Layout.setHorizontalGroup(
            sq52Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq52Layout.setVerticalGroup(
            sq52Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq52);
        sq52.setBounds(540, 180, 40, 40);

        sq53.setBackground(Color.blue);
        sq53.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq53.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq53Layout = new GroupLayout(sq53);
        sq53.setLayout(sq53Layout);
        sq53Layout.setHorizontalGroup(
            sq53Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq53Layout.setVerticalGroup(
            sq53Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq53);
        sq53.setBounds(500, 180, 40, 40);

        sq54.setBackground(Color.green);
        sq54.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq54.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq54Layout = new GroupLayout(sq54);
        sq54.setLayout(sq54Layout);
        sq54Layout.setHorizontalGroup(
            sq54Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq54Layout.setVerticalGroup(
            sq54Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq54);
        sq54.setBounds(460, 180, 40, 40);

        sq55.setBackground(Color.orange);
        sq55.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq55.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq55Layout = new GroupLayout(sq55);
        sq55.setLayout(sq55Layout);
        sq55Layout.setHorizontalGroup(
            sq55Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq55Layout.setVerticalGroup(
            sq55Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq55);
        sq55.setBounds(420, 180, 40, 40);

        sq56.setBackground(Color.red);
        sq56.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq56.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq56Layout = new GroupLayout(sq56);
        sq56.setLayout(sq56Layout);
        sq56Layout.setHorizontalGroup(
            sq56Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq56Layout.setVerticalGroup(
            sq56Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq56);
        sq56.setBounds(380, 180, 40, 40);

        sq57.setBackground(Color.yellow);
        sq57.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq57.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq57Layout = new GroupLayout(sq57);
        sq57.setLayout(sq57Layout);
        sq57Layout.setHorizontalGroup(
            sq57Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq57Layout.setVerticalGroup(
            sq57Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq57);
        sq57.setBounds(380, 220, 40, 40);

        sq58.setBackground(Color.blue);
        sq58.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq58.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq58Layout = new GroupLayout(sq58);
        sq58.setLayout(sq58Layout);
        sq58Layout.setHorizontalGroup(
            sq58Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq58Layout.setVerticalGroup(
            sq58Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq58);
        sq58.setBounds(380, 260, 40, 40);

        sq59.setBackground(Color.green);
        sq59.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq59.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq59Layout = new GroupLayout(sq59);
        sq59.setLayout(sq59Layout);
        sq59Layout.setHorizontalGroup(
            sq59Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq59Layout.setVerticalGroup(
            sq59Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq59);
        sq59.setBounds(340, 260, 40, 40);

        sq64.setBackground(Color.green);
        sq64.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq64.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq64Layout = new GroupLayout(sq64);
        sq64.setLayout(sq64Layout);
        sq64Layout.setHorizontalGroup(
            sq64Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq64Layout.setVerticalGroup(
            sq64Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq64);
        sq64.setBounds(140, 260, 40, 40);

        sq60.setBackground(Color.orange);
        sq60.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq60.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq60Layout = new GroupLayout(sq60);
        sq60.setLayout(sq60Layout);
        sq60Layout.setHorizontalGroup(
            sq60Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq60Layout.setVerticalGroup(
            sq60Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq60);
        sq60.setBounds(300, 260, 40, 40);

        sq61.setBackground(Color.red);
        sq61.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq61.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq61Layout = new GroupLayout(sq61);
        sq61.setLayout(sq61Layout);
        sq61Layout.setHorizontalGroup(
            sq61Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq61Layout.setVerticalGroup(
            sq61Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq61);
        sq61.setBounds(260, 260, 40, 40);

        sq62.setBackground(Color.yellow);
        sq62.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq62.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq62Layout = new GroupLayout(sq62);
        sq62.setLayout(sq62Layout);
        sq62Layout.setHorizontalGroup(
            sq62Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq62Layout.setVerticalGroup(
            sq62Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq62);
        sq62.setBounds(220, 260, 40, 40);

        sq63.setBackground(Color.blue);
        sq63.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq63.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq63Layout = new GroupLayout(sq63);
        sq63.setLayout(sq63Layout);
        sq63Layout.setHorizontalGroup(
            sq63Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq63Layout.setVerticalGroup(
            sq63Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq63);
        sq63.setBounds(180, 260, 40, 40);

        sq68.setBackground(Color.blue);
        sq68.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq68.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq68Layout = new GroupLayout(sq68);
        sq68.setLayout(sq68Layout);
        sq68Layout.setHorizontalGroup(
            sq68Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq68Layout.setVerticalGroup(
            sq68Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq68);
        sq68.setBounds(140, 100, 40, 40);

        sq73.setBackground(Color.blue);
        sq73.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq73.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq73Layout = new GroupLayout(sq73);
        sq73.setLayout(sq73Layout);
        sq73Layout.setHorizontalGroup(
            sq73Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq73Layout.setVerticalGroup(
            sq73Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq73);
        sq73.setBounds(340, 100, 40, 40);

        sq75.setBackground(Color.orange);
        sq75.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq75.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq75Layout = new GroupLayout(sq75);
        sq75.setLayout(sq75Layout);
        sq75Layout.setHorizontalGroup(
            sq75Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq75Layout.setVerticalGroup(
            sq75Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq75);
        sq75.setBounds(340, 20, 40, 40);

        sq80.setBackground(Color.orange);
        sq80.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq80.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq80Layout = new GroupLayout(sq80);
        sq80.setLayout(sq80Layout);
        sq80Layout.setHorizontalGroup(
            sq80Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq80Layout.setVerticalGroup(
            sq80Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq80);
        sq80.setBounds(540, 20, 40, 40);

        sq81.setBackground(Color.red);
        sq81.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq81.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq81Layout = new GroupLayout(sq81);
        sq81.setLayout(sq81Layout);
        sq81Layout.setHorizontalGroup(
            sq81Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq81Layout.setVerticalGroup(
            sq81Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq81);
        sq81.setBounds(540, 60, 40, 40);

        //grandmasHouse.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        //grandmasHouse.setPreferredSize(new Dimension(80, 80));

        GroupLayout grandmasHouseLayout = new GroupLayout(grandmasHouse);
        grandmasHouse.setLayout(grandmasHouseLayout);
        grandmasHouseLayout.setHorizontalGroup(
            grandmasHouseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grandmasHouseLayout.setVerticalGroup(
            grandmasHouseLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(grandmasHouse);
        grandmasHouse.setBounds(940, 40, 80, 80);

        sq87.setBackground(Color.yellow);
        sq87.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq87.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq87Layout = new GroupLayout(sq87);
        sq87.setLayout(sq87Layout);
        sq87Layout.setHorizontalGroup(
            sq87Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq87Layout.setVerticalGroup(
            sq87Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq87);
        sq87.setBounds(780, 60, 40, 40);

        sq86.setBackground(Color.red);
        sq86.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq86.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq86Layout = new GroupLayout(sq86);
        sq86.setLayout(sq86Layout);
        sq86Layout.setHorizontalGroup(
            sq86Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq86Layout.setVerticalGroup(
            sq86Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq86);
        sq86.setBounds(740, 60, 40, 40);

        sq85.setBackground(Color.orange);
        sq85.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq85.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq85Layout = new GroupLayout(sq85);
        sq85.setLayout(sq85Layout);
        sq85Layout.setHorizontalGroup(
            sq85Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq85Layout.setVerticalGroup(
            sq85Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq85);
        sq85.setBounds(700, 60, 40, 40);

        sq84.setBackground(Color.green);
        sq84.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq84.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq84Layout = new GroupLayout(sq84);
        sq84.setLayout(sq84Layout);
        sq84Layout.setHorizontalGroup(
            sq84Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq84Layout.setVerticalGroup(
            sq84Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq84);
        sq84.setBounds(660, 60, 40, 40);

        sq82.setBackground(Color.yellow);
        sq82.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq82.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq82Layout = new GroupLayout(sq82);
        sq82.setLayout(sq82Layout);
        sq82Layout.setHorizontalGroup(
            sq82Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq82Layout.setVerticalGroup(
            sq82Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq82);
        sq82.setBounds(580, 60, 40, 40);

        sq83.setBackground(Color.blue);
        sq83.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq83.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq83Layout = new GroupLayout(sq83);
        sq83.setLayout(sq83Layout);
        sq83Layout.setHorizontalGroup(
            sq83Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq83Layout.setVerticalGroup(
            sq83Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq83);
        sq83.setBounds(620, 60, 40, 40);

        sq76.setBackground(Color.red);
        sq76.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq76.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq76Layout = new GroupLayout(sq76);
        sq76.setLayout(sq76Layout);
        sq76Layout.setHorizontalGroup(
            sq76Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq76Layout.setVerticalGroup(
            sq76Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq76);
        sq76.setBounds(380, 20, 40, 40);

        sq77.setBackground(Color.yellow);
        sq77.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq77.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq77Layout = new GroupLayout(sq77);
        sq77.setLayout(sq77Layout);
        sq77Layout.setHorizontalGroup(
            sq77Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq77Layout.setVerticalGroup(
            sq77Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq77);
        sq77.setBounds(420, 20, 40, 40);

        sq78.setBackground(Color.blue);
        sq78.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq78.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq78Layout = new GroupLayout(sq78);
        sq78.setLayout(sq78Layout);
        sq78Layout.setHorizontalGroup(
            sq78Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq78Layout.setVerticalGroup(
            sq78Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq78);
        sq78.setBounds(460, 20, 40, 40);

        sq79.setBackground(Color.green);
        sq79.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq79.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq79Layout = new GroupLayout(sq79);
        sq79.setLayout(sq79Layout);
        sq79Layout.setHorizontalGroup(
            sq79Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq79Layout.setVerticalGroup(
            sq79Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq79);
        sq79.setBounds(500, 20, 40, 40);

        sq72.setBackground(Color.yellow);
        sq72.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq72.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq72Layout = new GroupLayout(sq72);
        sq72.setLayout(sq72Layout);
        sq72Layout.setHorizontalGroup(
            sq72Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq72Layout.setVerticalGroup(
            sq72Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq72);
        sq72.setBounds(300, 100, 40, 40);

        sq71.setBackground(Color.red);
        sq71.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq71.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq71Layout = new GroupLayout(sq71);
        sq71.setLayout(sq71Layout);
        sq71Layout.setHorizontalGroup(
            sq71Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq71Layout.setVerticalGroup(
            sq71Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq71);
        sq71.setBounds(260, 100, 40, 40);

        sq70.setBackground(Color.orange);
        sq70.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq70.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq70Layout = new GroupLayout(sq70);
        sq70.setLayout(sq70Layout);
        sq70Layout.setHorizontalGroup(
            sq70Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq70Layout.setVerticalGroup(
            sq70Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq70);
        sq70.setBounds(220, 100, 40, 40);

        sq69.setBackground(Color.green);
        sq69.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq69.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq69Layout = new GroupLayout(sq69);
        sq69.setLayout(sq69Layout);
        sq69Layout.setHorizontalGroup(
            sq69Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq69Layout.setVerticalGroup(
            sq69Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq69);
        sq69.setBounds(180, 100, 40, 40);

        sq67.setBackground(Color.yellow);
        sq67.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq67.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq67Layout = new GroupLayout(sq67);
        sq67.setLayout(sq67Layout);
        sq67Layout.setHorizontalGroup(
            sq67Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq67Layout.setVerticalGroup(
            sq67Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq67);
        sq67.setBounds(140, 140, 40, 40);

        sq66.setBackground(Color.red);
        sq66.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq66.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq66Layout = new GroupLayout(sq66);
        sq66.setLayout(sq66Layout);
        sq66Layout.setHorizontalGroup(
            sq66Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq66Layout.setVerticalGroup(
            sq66Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq66);
        sq66.setBounds(140, 180, 40, 40);

        sq65.setBackground(Color.orange);
        sq65.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq65.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq65Layout = new GroupLayout(sq65);
        sq65.setLayout(sq65Layout);
        sq65Layout.setHorizontalGroup(
            sq65Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq65Layout.setVerticalGroup(
            sq65Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq65);
        sq65.setBounds(140, 220, 40, 40);

        sq88.setBackground(Color.blue);
        sq88.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq88.setMinimumSize(new Dimension(20, 20));
        sq88.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq88Layout = new GroupLayout(sq88);
        sq88.setLayout(sq88Layout);
        sq88Layout.setHorizontalGroup(
            sq88Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        sq88Layout.setVerticalGroup(
            sq88Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        _frame.add(sq88);
        sq88.setBounds(820, 60, 40, 40);

        sq89.setBackground(Color.green);
        sq89.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq89.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq89Layout = new GroupLayout(sq89);
        sq89.setLayout(sq89Layout);
        sq89Layout.setHorizontalGroup(
            sq89Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq89Layout.setVerticalGroup(
            sq89Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq89);
        sq89.setBounds(860, 60, 40, 40);

        sq90.setBackground(Color.orange);
        sq90.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq90.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq90Layout = new GroupLayout(sq90);
        sq90.setLayout(sq90Layout);
        sq90Layout.setHorizontalGroup(
            sq90Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq90Layout.setVerticalGroup(
            sq90Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq90);
        sq90.setBounds(900, 60, 40, 40);

        sq15.setBackground(Color.orange);
        sq15.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq15.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq15Layout = new GroupLayout(sq15);
        sq15.setLayout(sq15Layout);
        sq15Layout.setHorizontalGroup(
            sq15Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq15Layout.setVerticalGroup(
            sq15Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq15);
        sq15.setBounds(420, 500, 40, 40);

        sq42.setBackground(Color.yellow);
        sq42.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq42.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq42Layout = new GroupLayout(sq42);
        sq42.setLayout(sq42Layout);
        sq42Layout.setHorizontalGroup(
            sq42Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq42Layout.setVerticalGroup(
            sq42Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq42);
        sq42.setBounds(820, 220, 40, 40);

        sq74.setBackground(Color.green);
        sq74.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        sq74.setPreferredSize(new Dimension(40, 40));

        GroupLayout sq74Layout = new GroupLayout(sq74);
        sq74.setLayout(sq74Layout);
        sq74Layout.setHorizontalGroup(
            sq74Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sq74Layout.setVerticalGroup(
            sq74Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        _frame.add(sq74);
        sq74.setBounds(340, 60, 40, 40);

//////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////
//Current deck settings
        deckArea.setPreferredSize(new Dimension(300, 180));

        _frame.add(deckArea);
        deckArea.setBounds(780, 360, 300, 180);
        CardDeckGUILayout cardDeck = new CardDeckGUILayout();
        deckArea.add(cardDeck);
////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////

    }// </editor-fold>//GEN-END:initComponents

////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////
//Deck event handler
    private void deckMouseClicked(MouseEvent evt) {//GEN-FIRST:event_deckMouseClicked
        // TODO add your handling code here:
    }
///////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////


    // Variables declaration
    private JFrame _frame;
  ////////////////////////////////////////////////////
    private JPanel deckArea;
  ////////////////////////////////////////////////////
    private JPanel grandmasHouse;
    private JPanel sq1;
    private JPanel sq10;
    private JPanel sq11;
    private JPanel sq12;
    private JPanel sq13;
    private JPanel sq14;
    private JPanel sq15;
    private JPanel sq16;
    private JPanel sq17;
    private JPanel sq18;
    private JPanel sq19;
    private JPanel sq2;
    private JPanel sq20;
    private JPanel sq21;
    private JPanel sq22;
    private JPanel sq23;
    private JPanel sq24;
    private JPanel sq25;
    private JPanel sq26;
    private JPanel sq27;
    private JPanel sq28;
    private JPanel sq29;
    private JPanel sq3;
    private JPanel sq30;
    private JPanel sq31;
    private JPanel sq32;
    private JPanel sq33;
    private JPanel sq34;
    private JPanel sq35;
    private JPanel sq36;
    private JPanel sq37;
    private JPanel sq38;
    private JPanel sq39;
    private JPanel sq4;
    private JPanel sq40;
    private JPanel sq41;
    private JPanel sq42;
    private JPanel sq43;
    private JPanel sq44;
    private JPanel sq45;
    private JPanel sq46;
    private JPanel sq47;
    private JPanel sq48;
    private JPanel sq49;
    private JPanel sq5;
    private JPanel sq50;
    private JPanel sq51;
    private JPanel sq52;
    private JPanel sq53;
    private JPanel sq54;
    private JPanel sq55;
    private JPanel sq56;
    private JPanel sq57;
    private JPanel sq58;
    private JPanel sq59;
    private JPanel sq6;
    private JPanel sq60;
    private JPanel sq61;
    private JPanel sq62;
    private JPanel sq63;
    private JPanel sq64;
    private JPanel sq65;
    private JPanel sq66;
    private JPanel sq67;
    private JPanel sq68;
    private JPanel sq69;
    private JPanel sq7;
    private JPanel sq70;
    private JPanel sq71;
    private JPanel sq72;
    private JPanel sq73;
    private JPanel sq74;
    private JPanel sq75;
    private JPanel sq76;
    private JPanel sq77;
    private JPanel sq78;
    private JPanel sq79;
    private JPanel sq8;
    private JPanel sq80;
    private JPanel sq81;
    private JPanel sq82;
    private JPanel sq83;
    private JPanel sq84;
    private JPanel sq85;
    private JPanel sq86;
    private JPanel sq87;
    private JPanel sq88;
    private JPanel sq89;
    private JPanel sq9;
    private JPanel sq90;
    private JPanel start;
    ////////////////////////////////////////////////////////////////

    // End of variables declaration//GEN-END:variables
}
